baseurl = "https://litegapps.github.io"
title = "Android News Update"
contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "public"
languageCode = "en"
resourceDir = "../resources"
DefaultContentLanguage = "en"
Paginate     = false
theme        = "bootstrap-5"

PygmentsCodeFences = true
PygmentsStyle      = "monokai"


keywords = [
    "Android", "Custom Rom", "Magisk",
    "magisk module", "ksu", "kernelsu", "kernel", "android experience", 
    "Tutorial Android", "android news", "best magisk module"
  ]

 buildFuture = true

[author]
     name = "wahyu6070"
     
[sitemap]
  changefreq = "always"
  priority = 0.8
  filename = "sitemap.xml"
#[permalinks]
#  news     = ":section/:year/:month/:day/:slug"
  
[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = "Read the latest news about Android | Custom Rom | Kernel | Tutorial | Magisk Module | kernelsu"
  recent_posts_number = 3
